# Generated by Django 5.1.4 on 2024-12-09 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_text', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=100)),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('dbpedia_uri', models.URLField(blank=True, null=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='NEL_app.text')),
            ],
        ),
    ]
