# Generated by Django 5.1.4 on 2024-12-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NEL_app', '0002_entity_probabilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='dbpedia_uri',
            new_name='uri',
        ),
    ]
