# Generated by Django 5.1.4 on 2024-12-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NEL_app', '0003_rename_dbpedia_uri_entity_uri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='entity_text',
            new_name='entity_label',
        ),
    ]
