# Generated by Django 5.1.4 on 2024-12-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NEL_app', '0004_rename_entity_text_entity_entity_label'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entity',
            new_name='FoundEntity',
        ),
    ]
